MAP=0
ODE=1
STROBE=2
POINCARE=3
MODE={'map':MAP,'ode':ODE,'strobe':STROBE,'Poincare':POINCARE}

N_EIGEN_TYPES=6

REAL_STABLE=0
REAL_NEUTRAL=1
REAL_UNSTABLE=2
COMPLEX_STABLE=3
COMPLEX_NEUTRAL=4
COMPLEX_UNSTABLE=5

EIGEN_INDEX={'RS':REAL_STABLE,'RN':REAL_NEUTRAL,'RU':REAL_UNSTABLE,
             'CS':COMPLEX_STABLE,'CN':COMPLEX_NEUTRAL,'CU':COMPLEX_UNSTABLE}
EIGEN_TYPE=['RS','RN','RU','CS','CN','CU']

N_FLOQUET_TYPES=9

REAL_POSITIVE_STABLE=0
REAL_POSITIVE_NEUTRAL=1
REAL_POSITIVE_UNSTABLE=2
COMPLEX_STABLE=3
COMPLEX_NEUTRAL=4
COMPLEX_UNSTABLE=5
REAL_NEGATIVE_STABLE=6
REAL_NEGATIVE_NEUTRAL=7
REAL_NEGATIVE_UNSTABLE=8

FLOQUET_INDEX={'RPS':REAL_POSITIVE_STABLE,'RPN':REAL_POSITIVE_NEUTRAL,'RPU':REAL_POSITIVE_UNSTABLE,
               'CS':COMPLEX_STABLE,'CN':COMPLEX_NEUTRAL,'CU':COMPLEX_UNSTABLE,
               'RNS':REAL_NEGATIVE_STABLE,'RNN':REAL_NEGATIVE_NEUTRAL,'RNU':REAL_NEGATIVE_UNSTABLE}
FLOQUET_TYPE=['RPS','RPN','RPU','CS','CN','CU','RNS','RNN','RNU']
