X_SCREEN_COORDINATE=0x100
Y_SCREEN_COORDINATE=0x200
Z_SCREEN_COORDINATE=0x400

X_COORDINATE=0x1
Y_COORDINATE=0x2
Z_COORDINATE=0x4
C_COORDINATE=0x8
T_COORDINATE=0x10
ALL_COORDINATES=0x1F

COORDINATE_FLAG={'x':X_COORDINATE, 'y':Y_COORDINATE, 'z':Z_COORDINATE,
                 'c':C_COORDINATE, 't':T_COORDINATE, 'all':ALL_COORDINATES, 
                 'x_screen':X_SCREEN_COORDINATE,
                 'y_screen':Y_SCREEN_COORDINATE,
                 'z_screen':Z_SCREEN_COORDINATE}

X_INDEX=0
Y_INDEX=1
Z_INDEX=2
C_INDEX=3
T_INDEX=4

COORDINATE_INDEX={'x':X_INDEX,'y':Y_INDEX,'z':Z_INDEX,'c':C_INDEX,'t':T_INDEX}

COORDINATE_NAME=['x','y','z','c','t']

N_COORDINATES=5

XY=X_COORDINATE|Y_COORDINATE
XYC=X_COORDINATE|Y_COORDINATE|C_COORDINATE
XYT=X_COORDINATE|Y_COORDINATE|T_COORDINATE
XYCT=X_COORDINATE|Y_COORDINATE|C_COORDINATE|T_COORDINATE
XYZ=X_COORDINATE|Y_COORDINATE|Z_COORDINATE
XYZC=X_COORDINATE|Y_COORDINATE|Z_COORDINATE|C_COORDINATE
XYZT=X_COORDINATE|Y_COORDINATE|Z_COORDINATE|T_COORDINATE
XYZCT=ALL_COORDINATES

VIEW_TYPE={'xy':XY,'xyc':XYC,'xyt':XYT,
           'xyct':XYCT,'xyz':XYZ,'xyzc':XYZC,
           'xyzt':XYZT,'xyzct':XYZCT}

DOT=0
PLUS=1
CROSS=2
RING=3
RDOT=4
RPLUS=5
RCROSS=6
QUAD=7
QDOT=8
QPLUS=9
QCROSS=10
HASH=11
STAR=12
NONE=13

POINT_TYPE={'dot':DOT,'plus':PLUS,'cross':CROSS,'ring':RING,
            'rdot':RDOT,'rplus':RPLUS,'rcross':RCROSS,'quad':QUAD,
            'qdot':QDOT,'qplus':QPLUS,'qcross':QCROSS,'hash':HASH,
            'star':STAR,'none':NONE}
